### ISSUE TITLE
output_layer(s) syntax error in Keras example

### ISSUE THREAD

**Issue by gianlucacientanni** [kmkolasinski/receptivefield#3]
Hi kmkolasinski,

I'm using:
- python v3.6
- keras v2.2.2 
and I tried to use your example provided in the receptivefield documentation but came across this error when running the compute function:

  File "<input>", line 4, in <module>
TypeError: compute() got an unexpected keyword argument 'output_layer'

Solution:

**Original**:
rf_params = rf.compute(
    input_shape=image.shape, 
    input_layer='input_image', 
    output_layer='feature_grid'
)

**Fixed**:
rf_params = rf.compute(
    input_shape=image.shape, 
    input_layer='input_image', 
    output_layers=['feature_grid']
)

Thanks,

Gianluca

**Comment by kmkolasinski** [comment]
Hi, thank you for your feedback,  however you should look at  official repository for receptivefield i.e. https://github.com/fornaxai/receptivefield 

I believe, this problem has been already fixed there.
